import { Config } from '../types';

export const DEFAULT_CONFIG: Config = {
  categories: {
    图片: [
      '.jpg',
      '.jpeg',
      '.png',
      '.gif',
      '.bmp',
      '.svg',
      '.webp',
      '.ico',
      '.tiff',
      '.raw',
      '.heic',
    ],
    视频: [
      '.mp4',
      '.avi',
      '.mkv',
      '.mov',
      '.wmv',
      '.flv',
      '.webm',
      '.m4v',
      '.3gp',
      '.ts',
      '.mts',
    ],
    音频: [
      '.mp3',
      '.wav',
      '.flac',
      '.aac',
      '.ogg',
      '.wma',
      '.m4a',
      '.opus',
      '.aiff',
    ],
    文档: [
      '.pdf',
      '.doc',
      '.docx',
      '.txt',
      '.rtf',
      '.odt',
      '.pages',
      '.epub',
      '.mobi',
    ],
    表格: ['.xls', '.xlsx', '.csv', '.ods', '.numbers'],
    演示文稿: ['.ppt', '.pptx', '.odp', '.key'],
    压缩包: [
      '.zip',
      '.rar',
      '.7z',
      '.tar',
      '.gz',
      '.bz2',
      '.xz',
      '.dmg',
      '.iso',
    ],
    程序: ['.exe', '.msi', '.app', '.deb', '.rpm', '.pkg', '.dmg', '.appimage'],
    代码: [
      '.js',
      '.html',
      '.css',
      '.py',
      '.java',
      '.cpp',
      '.c',
      '.php',
      '.rb',
      '.go',
      '.rs',
      '.swift',
      '.kt',
    ],
    字体: ['.ttf', '.otf', '.woff', '.woff2', '.eot'],
    其他: [],
  },
};
