import { Config } from '../types';

export const DEFAULT_CONFIG: Config = {
  categories: {
    Images: [
      '.jpg',
      '.jpeg',
      '.png',
      '.gif',
      '.bmp',
      '.svg',
      '.webp',
      '.ico',
      '.tiff',
      '.raw',
      '.heic',
    ],
    Video: [
      '.mp4',
      '.avi',
      '.mkv',
      '.mov',
      '.wmv',
      '.flv',
      '.webm',
      '.m4v',
      '.3gp',
      '.ts',
      '.mts',
    ],
    Audio: [
      '.mp3',
      '.wav',
      '.flac',
      '.aac',
      '.ogg',
      '.wma',
      '.m4a',
      '.opus',
      '.aiff',
    ],
    Documents: [
      '.pdf',
      '.doc',
      '.docx',
      '.txt',
      '.rtf',
      '.odt',
      '.pages',
      '.epub',
      '.mobi',
    ],
    Spreadsheets: ['.xls', '.xlsx', '.csv', '.ods', '.numbers'],
    Presentations: ['.ppt', '.pptx', '.odp', '.key'],
    Archives: [
      '.zip',
      '.rar',
      '.7z',
      '.tar',
      '.gz',
      '.bz2',
      '.xz',
      '.dmg',
      '.iso',
    ],
    Programs: [
      '.exe',
      '.msi',
      '.app',
      '.deb',
      '.rpm',
      '.pkg',
      '.dmg',
      '.appimage',
    ],
    Code: [
      '.js',
      '.html',
      '.css',
      '.py',
      '.java',
      '.cpp',
      '.c',
      '.php',
      '.rb',
      '.go',
      '.rs',
      '.swift',
      '.kt',
    ],
    Fonts: ['.ttf', '.otf', '.woff', '.woff2', '.eot'],
  },
};
