name: 'Check for Updates'

on:
  schedule:
    # 每天UTC时间10:00检查一次 (相当于北京时间18:00)
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for security updates
        run: |
          echo "Checking for security updates..."
          
          # 检查Rust依赖
          if command -v cargo-audit >/dev/null 2>&1; then
            cd src-tauri
            cargo audit
          else
            echo "cargo-audit not found, installing..."
            cargo install cargo-audit
            cd src-tauri
            cargo audit
          fi
          
          # 检查Node.js依赖
          npm audit --audit-level moderate

      - name: Check for dependency updates
        run: |
          echo "Checking for dependency updates..."
          
          # 检查Rust依赖更新
          cd src-tauri
          cargo update --dry-run
          
          # 检查Node.js依赖更新
          cd ..
          npm outdated || true

      - name: Create issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security vulnerabilities detected',
              body: 'The scheduled security check found vulnerabilities. Please review the workflow logs and update dependencies as needed.',
              labels: ['security', 'dependencies']
            })